name: Bump Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Install cocogitto
        uses: cocogitto/cocogitto-action@v3
        with:
          check: false

      - name: Configure git
        run: |
          git config user.name 'your-app-name[bot]'
          git config user.email 'your-app-id+your-app-name[bot]@users.noreply.github.com'

      - name: Bump version
        id: bump
        run: |
          # Check if there are any conventional commits since last tag
          if cog check --from-latest-tag; then
            # Bump version based on conventional commits
            cog bump --auto

            # Get the new version
            # test
            VERSION=$(cog get-version)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "bumped=true" >> $GITHUB_OUTPUT

            # Create and push tag
            git push origin main --tags

            echo "✅ Bumped version to $VERSION"
          else
            echo "❌ No conventional commits found since last tag"
            echo "bumped=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release (Optional)
        if: steps.bump.outputs.bumped == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.version }}
          generate_release_notes: true
          token: ${{ steps.app-token.outputs.token }}
